02-app - 02-api-reference - 02-file-conventions - page.mdx
Nextjs-kr/Nextjs.kr pull request #205
Opened 2023-06-23 02:47 UTC by hanyugeon

## 기여자용

### 문서 개선

- PR을 열기 전에 `pnpm prettier-fix`를 실행하여 서식 문제를 해결합니다. - 문서 기여 가이드를 읽고 문서 지침을 따르는지 확인하세요: https://github.com/Nextjs-kr/Nextjs.ko/blob/main/packages/next/README.md

## Progress

- [x] `pnpm prettier-fix`
- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

[//]: # '-->'

2023-06-23 02:49 UTC, hanyugeon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +> **알아두면 좋은 정보**
이전 PR들을 참고해보니
`Good to know` 를 `참고` 또는 `알아두면 좋은 점` 으로 번역되어있었으나
[리드미](https://github.com/Nextjs-kr/Nextjs.kr#%EC%B0%B8%EA%B3%A0)에서는 `알아두면 좋은 정보`로 표기되어있어 일단 리드미 내용대로 작성하였습니다.

2023-06-23 02:50 UTC, hanyugeon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +루트 세그먼트에서 해당 페이지까지의 [동적 루트 파라미터](/docs/app/building-your-application/routing/dynamic-routes)가 포함된 객체입니다. 다음 예제를 보세요.
root segment를 발음 그대로 루트 세그먼트로 번역하였는데 괜찮을지

여러분들의 의견이 궁금합니다.

2023-06-23 02:55 UTC, hanyugeon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +루트 세그먼트에서 해당 페이지까지의 [동적 루트 파라미터](/docs/app/building-your-application/routing/dynamic-routes)가 포함된 객체입니다. 다음 예제를 보세요.
변역한 `루트 세그먼트(root segment)`와 `동적 루트 파라미터(dynamic route parameters)`에서

한글로 작성된 `루트`가
영어에서는 각각 `root`, `route`로 표기법이 달라
독자가 헷갈리지 않을까 걱정이네요 🤔 

여러분들의 의견이 궁금합니다.

2023-06-23 07:01 UTC, Jeremy-Kr commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +> **알아두면 좋은 정보**
![image](https://github.com/Nextjs-kr/Nextjs.kr/assets/110771206/3ee98dec-cc97-49d4-b42e-b0e08ad7df4c)

[링크](https://github.com/Nextjs-kr/Nextjs.kr/pull/140#discussion_r1237122900)에서 "알아두면 좋은 정보" 가 아닌 "참고" 가이드라인이 작성되어 있습니다~! "참고"로 변경 부탁드려요.

2023-06-23 07:04 UTC, Jeremy-Kr requested changes

2023-06-23 07:04 UTC, Jeremy-Kr commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +> **알아두면 좋은 정보**
![image](https://github.com/Nextjs-kr/Nextjs.kr/assets/110771206/3ee98dec-cc97-49d4-b42e-b0e08ad7df4c)

[링크1](https://github.com/Nextjs-kr/Nextjs.kr/pull/140#discussion_r1237122900), [링크2](https://github.com/Nextjs-kr/Nextjs.kr#%EC%B0%B8%EA%B3%A0)에서 "알아두면 좋은 정보" 가 아닌 "참고" 가이드라인이 작성되어 있습니다~! "참고"로 변경 부탁드려요.

2023-06-23 13:26 UTC, ChanghyeonYoon reviewed
수고하셨습니다! 리뷰 반영 부탁드립니다!

2023-06-23 13:26 UTC, ChanghyeonYoon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +### `params` (옵션)
옵션보단 선택사항 이 좋을 듯 합니당

2023-06-23 13:26 UTC, ChanghyeonYoon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +### `searchParams` (옵션)
선택사항

2023-06-23 13:26 UTC, ChanghyeonYoon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +현재 URL의 [검색 매개변수](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#parameters)가 포함된 객체입니다. 다음 예제를 보세요.
참고로 수정해주시고 parameters는 파라미터로 수정 부탁드립니다! 실제 업무에서 매개변수란 말보단 파라미터라도 그대로 읽는 경우가 많으니까요!

2023-06-24 02:52 UTC, KunHwanAhn commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +루트 세그먼트에서 해당 페이지까지의 [동적 루트 파라미터](/docs/app/building-your-application/routing/dynamic-routes)가 포함된 객체입니다. 다음 예제를 보세요.
다른 번역을 진행하다 비슷한 고민을 했었는데요, 한국어 맞춤법에 돌려보니 `라우터`로 쓰라는 이야기가 있긴하더라구요.
 `영어 -> 한글`로 변환한 것을 맛춤법 검사를 한 것이라, 일단은 라우터로 작업하긴 했는데 `라우트`로 가는 것도 좋아보입니다. 이것 확정해주시면 제 작업에서도 f/up하겠습니다! 🙇‍♂️

2023-06-24 02:54 UTC, KunHwanAhn commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +현재 URL의 [검색 매개변수](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#parameters)가 포함된 객체입니다. 다음 예제를 보세요.
@ChanghyeonYoon 
아래 PR에 남긴 코멘트 참고 부탁드립니다~! 🙏 
- https://github.com/Nextjs-kr/Nextjs.kr/pull/231#discussion_r1240577318

2023-06-24 09:18 UTC, hanyugeon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +루트 세그먼트에서 해당 페이지까지의 [동적 루트 파라미터](/docs/app/building-your-application/routing/dynamic-routes)가 포함된 객체입니다. 다음 예제를 보세요.
@blissful-y0 @KunHwanAhn 의견 감사합니다!! `route`는 `라우트`로 표기하는것으로 해보겠습니다!

2023-06-24 09:19 UTC, hanyugeon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +> **알아두면 좋은 정보**
오 `참고`로 바뀌었네요!! 반영하도록하겠습니다 감사합니다!

2023-06-24 09:20 UTC, hanyugeon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +### `params` (옵션)
이부분도 고민이였는데 옵션이 더 적절해 보이네요 감사합니다!!

2023-06-24 09:22 UTC, hanyugeon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +> **알아두면 좋은 정보**
변경 사항(https://github.com/Nextjs-kr/Nextjs.kr/commit/dec4c7122bc8402c1bed706793964c8f91a4d423)에 따라 `참고`로 번역하도록 하겠습니다!

2023-06-24 09:29 UTC, hanyugeon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +현재 URL의 [검색 매개변수](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#parameters)가 포함된 객체입니다. 다음 예제를 보세요.
@ChanghyeonYoon 이슈 템플릿에 [용어 확인](https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary) 링크에 있는 내용에 따라 `매개변수`로 작성하였는데
@KunHwanAhn 님이 언급해주신 링크처럼 자세한 내용이 궁금합니다!!

2023-06-25 03:51 UTC, ChanghyeonYoon commented on docs/02-app/02-api-reference/02-file-conventions/page.mdx
> +현재 URL의 [검색 매개변수](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#parameters)가 포함된 객체입니다. 다음 예제를 보세요.
앗 매개변수로 해주세요!!!제가 깜빡했네요 ㅠㅠ @hanyugeon

2023-06-26 10:42 UTC, hanyugeon commented
@ChanghyeonYoon 리뷰 부탁드립니다!!

2023-06-27 14:09 UTC, ChanghyeonYoon approved these changes
LGTM
수고하셨습니다! 추가로 하시고 싶은 티켓이 있다면 신청해주셔도 됩니다!

2023-06-27 14:09 UTC, merged