03-pages -> 01-building-your-application -> 03-data-fetching-> 06-building-forms.mdx 번역
Nextjs-kr/Nextjs.kr pull request #240
Opened 2023-06-24 10:03 UTC by Eunseo-jo

## 기여자용

### 문서 개선

- PR을 열기 전에 `pnpm prettier-fix`를 실행하여 서식 문제를 해결합니다. - 문서 기여 가이드를 읽고 문서 지침을 따르는지 확인하세요: https://github.com/Nextjs-kr/Nextjs.ko/blob/main/packages/next/README.md

## Progress

- [x] `pnpm prettier-fix`
- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

[//]: # '-->'

2023-06-24 12:58 UTC, HA-SEUNG-JEONG requested changes

2023-06-24 17:15 UTC, chaejunlee reviewed
정말 긴 문서 번역하시느라 수고 많으셨습니다..!!

눈에 보이는 수정 사항에 대해 코멘트를 남겼습니다. 확인해주시고 납득 가능하시다면 반영 부탁드립니다!

2023-06-24 17:15 UTC, chaejunlee commented on docs/03-pages/01-building-your-application/03-data-fetching/06-building-forms.mdx
> +JavaScript가 비활성화된 상태에서 제출 버튼을 누르면 이벤트가 트리거되어 폼 데이터를 수집하고 `action` 어트리뷰트에 정의된 대로 `POST` HTTP `method` 사용하여 폼 API 엔드포인트로 보냅니다. 폼의 `action`이 작동하는 방식으로 `/api/form` 엔드포인트로 리디렉션됩니다.
```suggestion
JavaScript가 비활성화된 상태에서 제출 버튼을 누르면 폼 데이터를 수집하고 폼 데이터를 `action` 어트리뷰트에 정의된 대로 `POST` HTTP `method` 사용하여 폼 API 엔드포인트로 보내는 이벤트가 발생합니다. 폼의 `action`이 작동하는 방식대로 `/api/form` 엔드포인트로 리다이렉트됩니다.
```

2023-06-24 17:15 UTC, chaejunlee commented on docs/03-pages/01-building-your-application/03-data-fetching/06-building-forms.mdx
> +> 여기에서 사용자 경험을 향상시키기 위해서 응답으로 사용자를 페이지로 리디렉션하고, 폼 제출에 대해 감사의 인사를 할 수 있습니다.
```suggestion
> 여기서 사용자 경험을 향상시키기 위해 응답으로써 폼을 제출해주셔서 감사하다는 페이지로 사용자를 리디렉트할 수 있습니다.
```

2023-06-24 17:15 UTC, chaejunlee commented on docs/03-pages/01-building-your-application/03-data-fetching/06-building-forms.mdx
> +    // 서버가 제출된 이름을 반환하면 폼이 작동한다는 의미입니다.
```suggestion
    // JSON으로 서버의 응답 데이터를 가져옵니다.  
    // 서버가 제출한 이름을 그대로 반환하면 폼 작동이 성공했다는 의미입니다.
```

2023-06-24 17:15 UTC, chaejunlee commented on docs/03-pages/01-building-your-application/03-data-fetching/06-building-forms.mdx
> +`handleSubmit()`함수는 아래 단계를 통해서 폼 데이터를 처리합니다.
```suggestion
`handleSubmit()` 함수는 아래 단계를 통해서 폼 데이터를 처리합니다.
```

2023-06-24 17:15 UTC, chaejunlee commented on docs/03-pages/01-building-your-application/03-data-fetching/06-building-forms.mdx
> +- 폼에서 `first` 와 `last` 값을 사용하여 `data` 라는 JavaScript 객체를 만듭니다.
```suggestion
- 폼에서 `first`와 `last` 값을 사용하여 `data`라는 JavaScript 객체를 만듭니다.
```

2023-06-24 17:15 UTC, chaejunlee commented on docs/03-pages/01-building-your-application/03-data-fetching/06-building-forms.mdx
>  - The basic HTML `form` element
```suggestion

```

삭제되지 않은 원문이 있네요!

2023-06-25 08:11 UTC, Eunseo-jo commented on docs/03-pages/01-building-your-application/03-data-fetching/06-building-forms.mdx
> +다음은 [JSX](https://react.dev/learn/writing-markup-with-jsx)를 사용하여 작성된 [React 함수형 컴포넌트](https://react.dev/reference/react/Component)의 동일한 폼입니다.
함수 컴포넌트로 수정하겠습니다-!

2023-06-25 08:22 UTC, closed without merging