docs/06-configuring/01-typescript
Nextjs-kr/Nextjs.kr pull request #332
Opened 2023-06-28 08:36 UTC by jiji-hoon96

## 기여자용

### 문서 개선

- PR을 열기 전에 `pnpm prettier-fix`를 실행하여 서식 문제를 해결합니다. - 문서 기여 가이드를 읽고 문서 지침을 따르는지 확인하세요: https://github.com/Nextjs-kr/Nextjs.ko/blob/main/packages/next/README.md

## Progress

- [] `pnpm prettier-fix`
- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

[//]: # '-->'

2023-06-30 00:12 UTC, haileyport commented
ref #93

2023-07-14 10:31 UTC, g2hhh2ee commented
수고하셨습니다:) 
Progress 체크 해주시고 리뷰도 확인해주세요 😊

2023-07-17 14:18 UTC, jiji-hoon96 commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +Next.js 13에는 **향상된 type 안전성**이 있습니다. 여기에는 하단 내용이 포함됩니다:
수정완료

2023-07-17 14:18 UTC, jiji-hoon96 commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +현재 실험적으로 지원되는 것은 동적 세그먼트를 포함한 모든 문자열 리터럴입니다. 리터럴이 아닌 문자열의 경우, 현재 `href`를 `as Route`로 수동으로 캐스팅해야 합니다:
수정완료

2023-07-17 14:19 UTC, jiji-hoon96 commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +create-next-app은 이제 기본적으로 TypeScript이 함께 제공됩니다.
수정완료

2023-07-17 14:19 UTC, jiji-hoon96 commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
>  description: Next.js provides a TypeScript-first development experience for building your React application.
수정완료

2023-07-19 11:50 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +[`사용자 지정 App`](/docs/pages/building-your-application/routing/custom-app)이 있는 경우, 기본 제공 유형인 `AppProps`를 사용하고 파일 이름을 './pages/\_app.tsx'로 변경하면 됩니다:
```suggestion
[`사용자 지정 App`](/docs/pages/building-your-application/routing/custom-app)이 있는 경우, 기본 제공 유형인 `AppProps`를 사용하고 파일 이름을 `./pages/\_app.tsx`로 변경하면 됩니다.
```

2023-07-19 11:50 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +'next.config.js' 파일은 바벨이나 타입스크립트에서 구문 분석되지 않으므로 자바스크립트 파일이어야 하지만, 아래와 같이 JSDoc을 사용하여 IDE에서 타입 검사를 추가할 수 있습니다:
```suggestion
`next.config.js` 파일은 바벨이나 타입스크립트에서 구문 분석되지 않으므로 자바스크립트 파일이어야 하지만, 아래와 같이 JSDoc을 사용하여 IDE에서 타입 검사를 추가할 수 있습니다.
```

2023-07-19 11:51 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +`next.config.js`를 열고 `typescript` 구성에서 `ignoreBuildErrors` 옵션을 활성화합니다:
```suggestion
`next.config.js`를 열고 `typescript` 구성에서 `ignoreBuildErrors` 옵션을 활성화합니다.
```

2023-07-19 11:54 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +다음은 API 경로에 기본 제공 유형을 사용하는 방법의 예입니다:
```suggestion
다음은 API 경로에 기본 제공 유형을 사용하는 방법의 예입니다.
```

2023-07-19 11:56 UTC, g2hhh2ee commented
리뷰 반영해주시느라 수고하셨습니다! 문서 전체적으로 누락된 ``기호와 수정되어야 할 : 기호 표시해뒀습니다 :)

2023-07-21 09:12 UTC, jiji-hoon96 commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +다음은 API 경로에 기본 제공 유형을 사용하는 방법의 예입니다:
수정완료

2023-07-21 09:12 UTC, jiji-hoon96 commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +`next.config.js`를 열고 `typescript` 구성에서 `ignoreBuildErrors` 옵션을 활성화합니다:
수정완료

2023-07-21 09:12 UTC, jiji-hoon96 commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +[`사용자 지정 App`](/docs/pages/building-your-application/routing/custom-app)이 있는 경우, 기본 제공 유형인 `AppProps`를 사용하고 파일 이름을 './pages/\_app.tsx'로 변경하면 됩니다:
수정완료

2023-07-21 09:12 UTC, jiji-hoon96 commented
@g2hhh2ee  수정완료했습니다. 번거롭게해서 죄송합니다

2023-08-01 23:11 UTC, jiji-hoon96 commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +props을 통해 서버와 클라이언트 컴포넌트 간에 데이터를 전달할 때에도 브라우저에서 사용할 수 있도록 데이터가 직렬화(문자열로 변환)됩니다. 하지만 특별한 유형이 필요하지 않습니다. 컴포넌트 간에 다른 프로퍼티를 전달할 때와 동일한 유형으로 전달됩니다.
좋습니다! 감사합니다

2023-08-01 23:11 UTC, jiji-hoon96 commented
수정사항 커밋완료했습니다

2023-08-17 07:56 UTC, g2hhh2ee requested changes

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +## 정적 유형 링크
```suggestion
## 정적 타입 링크
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +Next.js는 `next/link`를 사용할 때 오타 및 기타 오류를 방지하기 위해 링크를 정적으로 입력할 수 있어 페이지 간 탐색 시 유형 안전성이 향상됩니다.
```suggestion
Next.js는 `next/link`를 사용할 때 오타 및 다른 오류를 방지하고 페이지 간 탐색 시 타입 안전성을 향상시키기 위해 링크에 정적으로 타입을 지정할 수 있습니다.
```

`next/link`를 사용하여 오타나 다른 오류를 방지하며 페이지 간 탐색 시 타입 안전성을 향상시키는 것을 강조하면 의미가 더 잘 전달될 것 같습니다! 어떠실까요? 🙂

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +## 엔드투엔드 type 안전성
```suggestion
## 엔드투엔드 타입 안전성
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +[Next.js의 데이터 가져오기](/docs/app/building-your-application/data-fetching/fetching)는 이제 데이터베이스 또는 콘텐츠 제공업체 선택에 대한 규범적 제한 없이 엔드투엔드 type 안전성에 최대한 근접한 기능을 제공합니다.
```suggestion
[Next.js의 데이터 가져오기](/docs/app/building-your-application/data-fetching/fetching)는 이제 데이터베이스 또는 콘텐츠 제공업체 선택에 대한 규범적 제한 없이 엔드투엔드 타입 안전성에 최대한 근접한 기능을 제공합니다.
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +For _complete_ 엔드투엔드 type 안전성을 확보하려면 데이터베이스 또는 콘텐츠 제공업체가 타입스크립트를 지원해야 합니다. [ORM](https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping) 또는 type 안전 쿼리 빌더를 사용할 수 있습니다.
```suggestion
For _complete_ 엔드투엔드 타입 안전성을 확보하려면 데이터베이스 또는 콘텐츠 제공업체가 타입스크립트를 지원해야 합니다. [ORM](https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping) 또는 타입 안전 쿼리 빌더를 사용할 수 있습니다.
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +이전 버전의 TypeScript를 사용하는 경우 `'Promise<Element>' is not a valid JSX element`라는 유형 오류가 표시될 수 있습니다. 최신 버전의 TypeScript 및 `@types/react`로 업데이트하면 이 문제가 해결됩니다.
```suggestion
이전 버전의 TypeScript를 사용하는 경우 `'Promise<Element>' is not a valid JSX element`라는 타입 오류가 표시될 수 있습니다. 최신 버전의 TypeScript 및 `@types/react`로 업데이트하면 이 문제가 해결됩니다.
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +다음은 API 경로에 기본 제공 유형을 사용하는 방법의 예입니다.
```suggestion
다음은 API 경로에 내장된 타입을 사용하는 방법의 예입니다.
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +[`사용자 지정 App`](/docs/pages/building-your-application/routing/custom-app)이 있는 경우, 기본 제공 유형인 `AppProps`를 사용하고 파일 이름을 `./pages/_app.tsx`로 변경하면 됩니다.
```suggestion
[`사용자 지정 App`](/docs/pages/building-your-application/routing/custom-app)이 있는 경우, 내장된 `AppProps` 타입을 사용하고 파일 이름을 `./pages/_app.tsx`로 변경하면 됩니다.
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +## next.config.js Type 확인
```suggestion
## next.config.js 타입 확인
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +애플리케이션에 오류가 있는 경우에도 Next.js가 프로덕션 코드를 위험하게 생성하지 않게 하려면 기본 제공 type 검사 단계를 비활성화할 수 있습니다.
```suggestion
애플리케이션에 오류가 있는 경우에도 Next.js가 프로덕션 코드를 위험하게 생성하지 않게 하려면 내장된 타입 체킹 단계를 비활성화할 수 있습니다.
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +`v10.2.1` Next.js는 `tsconfig.json`에서 활성화하면 [증분 유형 검사](https://www.typescriptlang.org/tsconfig#incremental)를 지원하므로 대규모 애플리케이션에서 유형 검사 속도를 높이는 데 도움이 될 수 있습니다.
```suggestion
`v10.2.1` Next.js는 `tsconfig.json`에서 활성화하면 [점진적 타입 체크](https://www.typescriptlang.org/tsconfig#incremental)를 지원하므로 대규모 애플리케이션에서 유형 검사 속도를 높이는 데 도움이 될 수 있습니다.
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +| `v13.2.0` | 정적으로 입력된 링크는 베타 버전에서 사용할 수 있습니다.                                                                |
```suggestion
| `v13.2.0` | 정적 타입 링크는 베타 버전에서 사용할 수 있습니다.                                                                |
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +## 증분 Type 검사
```suggestion
## 점진적 타입 체크
```

2023-08-17 07:56 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +## 증분 Type 검사
Incremental type checking을 '점진적 타입 체크'로 번역하는 이유는 다음과 같습니다. 😊

우선, Incremental type checking은 TypeScript의 기능으로, 변경된 부분만을 다시 타입 체크하여 전체적인 속도를 향상시킵니다.

'증분형'은 작은 단위로 조금씩 더하거나 높이는 것을 의미하는 기술적인 용어입니다.
'점진적'은 변화나 개선을 조금씩 나누어 진행하거나 이루어지는 것을 나타내는데, 기술적인 의미에서도 타입 체크 과정이 단계적이고 조금씩 진행되는 것을 의미합니다.

이러한 이유로 '점진적 타입 체크'로 번역하는 것이 'incremental'의 의미를 보다 자연스럽게 전달하며, 기술적인 개념을 이해하기 쉽고 친숙한 표현이기도 합니다. 따라서 공식 문서에서도 '점진적 타입 체크'로 번역하여 사용하면 더욱 쉽게 이해될 것으로 생각됩니다.

2023-08-17 08:02 UTC, g2hhh2ee approved these changes
긴 피드백과 리뷰 하시느라 수고하셨습니다! 기여해주셔서 감사합니다 👍

2023-08-18 05:51 UTC, merged