docs: [WIP] 03-pages > 02-api-reference > 02-functions > get-static-props.mdx
Nextjs-kr/Nextjs.kr pull request #333
Opened 2023-06-28 08:59 UTC by NamJwong

작업 중이며, 각 챕터 단위로 커밋하여 올릴 예정입니다.
작업 과정에서의 리뷰 대환영입니다!

## 기여자용

### 문서 개선

- PR을 열기 전에 `pnpm prettier-fix`를 실행하여 서식 문제를 해결합니다. - 문서 기여 가이드를 읽고 문서 지침을 따르는지 확인하세요: https://github.com/Nextjs-kr/Nextjs.ko/blob/main/packages/next/README.md

## Progress

- [ ] `pnpm prettier-fix`
- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

[//]: # '-->'

2023-06-30 00:12 UTC, haileyport commented
ref #105

2023-07-07 01:10 UTC, haileyport reviewed
수고하셨습니다! 리뷰 반영 부탁드립니다~

2023-07-07 01:10 UTC, haileyport commented on docs/03-pages/02-api-reference/02-functions/get-static-props.mdx
> +description: `getStaticProps`를 위한 API 레퍼런스입니다. 'getStaticProps'를 사용하여 Next.js로 정적 페이지를 생성하는 방법에 대해 알아봅니다.
두 번째 getStaticProps를 백틱으로 감싸주세요!

2023-07-07 01:10 UTC, haileyport commented on docs/03-pages/02-api-reference/02-functions/get-static-props.mdx
> +`getStaticProps`에서 사용할 모듈을 최상위 스코프로 가져올 수 있습니다. 사용된 가져오기는 **클라이언트 측에서 번들링 되지 않습니다.** 즉, 데이터베이스에서 데이터를 가져오는 것을 포함하여 **서버측 코드를 'getStaticProps'에 직접 작성할 수 있습니다.**
두 번째로 나오는 getStaticProps을 백틱으로 감싸주세요!

2023-07-07 01:10 UTC, haileyport commented on docs/03-pages/02-api-reference/02-functions/get-static-props.mdx
> +| Name            | Description
컬럼명도 번역 부탁드립니다~

2023-08-02 05:40 UTC, yoo-jimin127 commented
@NamJwong 님 안녕하세요!
Next.js kr 리뷰 반영 확인 및 머지 담당자입니다!
번역 진행해주신 해당 [PR](https://github.com/Nextjs-kr/Nextjs.kr/pull/333)에서 충돌이 발생하고 있습니다.
최종 번역된 내용 바탕으로 해당 부분 충돌 해결 완료해주신 뒤, 
저를 멘션해주시면 바로 리뷰 진행한 뒤 머지하도록 하겠습니다!
감사합니다 :)

2023-08-03 12:13 UTC, yoo-jimin127 requested changes
@NamJwong 님 안녕하세요!
충돌 해결해주신 것 확인하였습니다 :) 
감사합니다!

머지를 진행하려 하였으나,
충돌 해결 과정 중에서 번역이 완료되어 머지된 문서들이 영문으로 원상복구되어 함께 스테이징되어 푸시된 것으로 확인됩니다 😂

@NamJwong 님께서 번역 진행해주신 파일인 get-static-props.mdx를 제외하고 기존 파일을은 [files changed](https://github.com/Nextjs-kr/Nextjs.kr/pull/333/files)에서 제외해주시기 바랍니다!
감사합니다 :)

2023-08-04 19:49 UTC, NamJwong commented
@yoo-jimin127  처음 충돌 해결 시 있었던 실수를 되돌려서 다시 올바르게 충돌 해결했습니다 번거롭게 해드려 죄송합니다😂

2023-08-05 05:21 UTC, yoo-jimin127 approved these changes
LGTM! 👍
여러 차례 수정 요청드려 번거로우셨을텐데,
수고 많으셨습니다☺️
추가로 번역 희망하시는 챕터의 경우 이슈에 남겨주세요!!

2023-08-05 05:21 UTC, merged