02-app > 01-building-your-application > 05-optimizing > 06-lazy-loading.mdx
Nextjs-kr/Nextjs.kr pull request #368
Opened 2023-06-30 05:30 UTC by dev-sese

## 기여자용

### 문서 개선

- PR을 열기 전에 `pnpm prettier-fix`를 실행하여 서식 문제를 해결합니다. - 문서 기여 가이드를 읽고 문서 지침을 따르는지 확인하세요: https://github.com/Nextjs-kr/Nextjs.ko/blob/main/packages/next/README.md

## Progress

- [ ] `pnpm prettier-fix`
- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

[//]: # '-->'

2023-06-30 09:09 UTC, haileyport commented
ref #14

2023-07-20 06:46 UTC, g2hhh2ee commented on docs/02-app/01-building-your-application/05-optimizing/06-lazy-loading.mdx
> +Next.js에서 지연 로딩을 구현하는 데는 두 가지 방법이 있습니다:
[모범사례](https://github.com/reactjs/ko.react.dev/wiki/Best-practices-for-translation#%EC%8C%8D%EC%A0%90%EC%9D%80-%EA%B1%B0%EC%9D%98-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 참고

문서 전체적으로 반영 부탁드립니다 :)

```suggestion
Next.js에서 지연 로딩을 구현하는 데는 두 가지 방법이 있습니다.
```

2023-07-20 06:47 UTC, g2hhh2ee commented
수고하셨습니다! 리뷰 확인 부탁드립니다 🙂

2023-09-06 11:16 UTC, ChanghyeonYoon commented
@dev-sese 리뷰 이후 작업이 몇일 동안 이뤄지지 않아 9월 13일까지 작업이 없을 경우 이슈를 close하고 새로운 분에게 할당하겠습니다!

2023-09-06 15:21 UTC, dev-sese commented
리뷰 사항을 이제야 확인했습니다. 리마인드 감사합니다!
Progress의 task도 체크 완료하였습니다.
감사합니다!

2023-09-08 06:08 UTC, yoo-jimin127 requested changes
안녕하세요 @dev-sese 님!
기여해주셔서 감사합니다 :)
추가적으로 번역 담당 챕터이셨던 `02-app > 01-building-your-application > 05-optimizing > 06-lazy-loading.mdx`를 제외하고, 나머지 PR에 함께 추적되어 올라온 4개의 파일은 제외해주시기 바라비다!

2023-10-06 05:52 UTC, ChanghyeonYoon commented
@dev-sese 
10/13 까지 충돌파일 해결 작업 진행 안될경우
이슈 클로즈하고 다른분에게 재할당 하겠습니다!

2023-10-09 12:15 UTC, dev-sese commented
안녕하세요 기존에 담당이 아니지만 추적되어 함께 올라간 파일들을 작업 전으로 원복하였습니다.
제가 git 사용이 미숙해 여전히 에러가 있을 수 있습니다ㅠㅠ
확인해보시고 수정사항이 있다면 말씀해주세요!

2023-10-09 14:05 UTC, yoo-jimin127 approved these changes
기여해주셔서 감사합니다.
추가적으로 할당 희망하시는 챕터의 경우 이슈에 작성 부탁드립니다!☺️

2023-10-09 14:06 UTC, merged