03-pages > 02-api-reference > 03-next-config-js > compress.mdx 번역
Nextjs-kr/Nextjs.kr pull request #382
Opened 2023-07-01 10:52 UTC by ryukyung

…x 번역

## 기여자용

### 문서 개선

- PR을 열기 전에 `pnpm prettier-fix`를 실행하여 서식 문제를 해결합니다. - 문서 기여 가이드를 읽고 문서 지침을 따르는지 확인하세요: https://github.com/Nextjs-kr/Nextjs.ko/blob/main/packages/next/README.md

## Progress #194 

- [ ] `pnpm prettier-fix`
- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

[//]: # '-->'

2023-07-24 16:02 UTC, chaejunlee approved these changes
기여해주셔서 감사합니다! 깔끔한 번역 확인했습니다! 바로 머지하도록 하겠습니다.

2023-07-24 16:04 UTC, chaejunlee requested changes
번역 요청을 `pages` 문서로 해주신 것으로 확인 됩니다! 그런데 `app` 문서를 번역해주셨네요 ㅠㅠ `app` 부분은 할당된 다른 분이 먼저 기여해주신 것으로 확인됩니다. 혹시 `pages` 문서로 다시 번역해주실 수 있을까요?

2023-08-08 12:13 UTC, chaejunlee approved these changes
리뷰 반영해주셔서 감사합니다! Approve 남기겠습니다!! 수고 많으셨습니다.

2023-08-09 04:03 UTC, yoo-jimin127 approved these changes
LGTM!! 수고 많으셨습니다 ☺️👍
추가로 번역 희망하시는 챕터의 경우 이슈에 작성해주셔도 됩니다!!

2023-08-09 04:03 UTC, merged

2023-08-09 04:04 UTC, yoo-jimin127 commented
ref #194