02-app > 01-building-your-application > 03-data-fetching > 04-server-actions.mdx
Nextjs-kr/Nextjs.kr pull request #388
Opened 2023-07-02 04:30 UTC by Geun-Oh

## 기여자용

### 문서 개선

- PR을 열기 전에 `pnpm prettier-fix`를 실행하여 서식 문제를 해결합니다. - 문서 기여 가이드를 읽고 문서 지침을 따르는지 확인하세요: https://github.com/Nextjs-kr/Nextjs.ko/blob/main/packages/next/README.md

## Progress

- [x] `pnpm prettier-fix`
- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

[//]: # '-->'

2023-07-02 10:31 UTC, HA-SEUNG-JEONG requested changes

2023-07-02 10:31 UTC, HA-SEUNG-JEONG commented on docs/02-app/01-building-your-application/03-data-fetching/04-server-actions.mdx
> +> - Server Actions는 리액트의 `experimental` 채널에서 사용되고 동작합니다.
```suggestion
> - Server Actions는 리액트의 `experimental` 채널에서 사용하고 동작합니다.
```

2023-07-02 10:31 UTC, HA-SEUNG-JEONG commented on docs/02-app/01-building-your-application/03-data-fetching/04-server-actions.mdx
> +`button`, `input type="submit"`, 그리고 `input type="image"`과 같은 요소에 존재하는 **Form Actions**을 다루기 위해 `formAction`을 사용할 수 있습니다. `formAction` 속성은 form의 `action` 보다 우선시됩니다.
```suggestion
`button`, `input type="submit"`, 그리고 `input type="image"`과 같은 요소에 존재하는 **Form Actions**을 다루기 위해 `formAction`을 사용할 수 있습니다. `formAction` 속성은 form의 `action` 보다 우선시 됩니다.
```

2023-07-03 01:55 UTC, haileyport commented
ref #34

2023-09-06 11:18 UTC, ChanghyeonYoon commented
@Geun-Oh 리뷰 이후 작업이 몇일 동안 이뤄지지 않아 9월 13일까지 작업이 없을 경우 이슈를 close하고 새로운 분에게 할당하겠습니다!

2023-09-06 16:52 UTC, Geun-Oh commented
@ChanghyeonYoon 엇 혹시 HA-SEUNG-JEONG님께서 리뷰해주신 사항에 대해서는 반영을 한 상태인데 이후에 제가 놓친 부분이 존재할까요..? 말씀 주시면 추가 작업 이어가겠습니다!

2023-09-07 02:49 UTC, ChanghyeonYoon commented
@Geun-Oh 착오가 있었던 것 같습니다! @sungh0lim 님께서 리뷰 진행해주실 거에요!

2023-09-07 02:50 UTC, Geun-Oh commented
> @Geun-Oh 착오가 있었던 것 같습니다! @sungh0lim 님께서 리뷰 진행해주실 거에요!

넵 감사합니다!

2023-09-07 03:43 UTC, sunghi1im commented
@HA-SEUNG-JEONG 님! 확인한번 부탁드리겠습니다. 🙇

2023-09-07 06:47 UTC, sungh0lim commented on docs/02-app/01-building-your-application/03-data-fetching/04-server-actions.mdx
> +[Server Actions](#server-actions) 는 리액트의 [Actions](#actions) 를 기반으로 구축된 Next.js의 **주요**한 기능 중 하나입니다. 이는 클라이언트 단의 Javascript 코드를 줄이고, 서버 단에서의 데이터 변경을 가능하게 하는 보다 발전된 형태의 기능입니다. 이는 서버 컴포넌트 내부에서 정의되거나 클라
```suggestion
[Server Actions](#server-actions) 는 리액트의 [Actions](#actions) 를 기반으로 구축된 Next.js의 **주요**한 기능 중 하나입니다. 이는 클라이언트 측의 Javascript 코드를 줄이고 서버 측의 데이터 변경을 가능하게 하는 보다 발전된 형태의 기능입니다. 이는 서버 컴포넌트 내부에서 정의되거나 클라이언트 컴포넌트에서 호출될 수 있습니다.
```

2023-09-07 06:48 UTC, sungh0lim commented on docs/02-app/01-building-your-application/03-data-fetching/04-server-actions.mdx
> +- 사용할 컴포넌트 내부 (오직 서버 컴포넌트에서)
```suggestion
- (서버 컴포넌트에서만) 사용할 컴포넌트 내부
```

2023-09-07 06:52 UTC, Geun-Oh commented
@sungh0lim  리뷰해주신 부분 확인했고, Suggestion 반영했습니다. 리뷰 반영 체크 또한 완료했습니다!

2023-09-08 06:05 UTC, yoo-jimin127 requested changes
@Geun-Oh 님 안녕하세요!
기여해주셔서 감사합니다 :)
현재 번역 진행해주신 `02-app > 01-building-your-application > 03-data-fetching > 04-server-actions.mdx`를 제외하고, 커밋이 함께 올라온 `pull_request_template.md`와 `README.md`, `pnpm-lock.yaml`의 경우 PR에서 배제 부탁드립니다!

2023-09-09 01:44 UTC, yoo-jimin127 approved these changes
LGTM!! 기여해주셔서 감사합니다 :)👍
추가적으로 번역 희망하시는 챕터의 경우 이슈에 남겨주세요!!

2023-09-09 01:44 UTC, merged