03-pages> 01-building-your-application>05-optimizing> 09-instrumentation.mdx 초안 작성
Nextjs-kr/Nextjs.kr pull request #427
Opened 2023-07-29 14:58 UTC by billy5982

## 기여자용

### 문서 개선

- PR을 열기 전에 `pnpm prettier-fix`를 실행하여 서식 문제를 해결합니다. - 문서 기여 가이드를 읽고 문서 지침을 따르는지 확인하세요: https://github.com/Nextjs-kr/Nextjs.ko/blob/main/packages/next/README.md

## Progress

- [ ] `pnpm prettier-fix`
- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/Nextjs-kr/Nextjs.kr/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/Nextjs-kr/Nextjs.kr/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

[//]: # '-->'

2023-07-29 15:00 UTC, billy5982 commented
ref #305

2023-08-01 09:33 UTC, marvelopers approved these changes

2023-08-01 09:38 UTC, marvelopers requested changes
@billy5982 코멘트 확인 부탁드립니다.

2023-08-01 09:38 UTC, marvelopers commented on docs/03-pages/01-building-your-application/05-optimizing/09-instrumentation.mdx
> +description: Next.js 앱에서 서버가 시작될 때 코드를 실행하기 위해 instrumentation을 사용하는 방법 알아보기
```suggestion
description: Next.js 앱에서 서버 시작 시 코드를 실행하는 데에 계측을 활용하는 방법 알아보기
```
instrumentation도 번역 부탁드립니다.

2023-08-01 23:58 UTC, marvelopers approved these changes

2023-08-01 23:58 UTC, merged